language: java
before_script: cd 12f_app
script: mvn clean install
deploy:
  edge: true
  provider: cloudfoundry
  username: toomas.pappel@smit.ee
  api: https://api.run.pivotal.io
  organization: tp
  space: development
dd:
  secure: bloJvt3Nbldu3N40EbVfDtbAlmbQM14CB5WdTOODb9PffiQshKvSc069IB7or3Os5MT+Ux1tHuFWn8cA6iJ1pWNDUSedRc4OpsUv6q8k1/oPf1ZKPjZfiqJ+QmXUCAdtZ4sGpP7BhD/k34OFlWWN2MnjMatJW52QpeIQJgzzvbEn/ZzoJ11XhFYU4xuuA0/83JzIi7JT+94/fSHvNvjw2pHzpRDYzlQsKeFx9rnkRbIRNOU98CZxngbJLs9id1XKt+BZU/LzDEA7P7at0nNEPPpHCZ3sZwPv/p3/wjkn5wi62z+8ebAc+OJKg9cKgLRE6TuaZdwz/tyAVCP3YlKMojDVWclSqGSmyPg7mknYk4P70PGDZQtPXBOIvg6NB17b1PJ+MVv07oBfFnUtDRmET+Y/F6OLHrbNXGBU9RYQRFD7JLJrfFt/7lvWlnu3ilKtEMPU1QnfcFmWd2PhMC1WYJPCaEMOfjVarAhk9ciH2oJKvyvSM/YydW+tIVmBoFKy2dJFYydBLDxbL38oONUw0ae6L++rxo7WIJPP3/y+ARhQWEg0M/H8JSSPgOhGW/AxPNN+OOmQcCHEderQSfeDbi/AtlbnjvIlNNpX/RvpqwsJLj9y49gFx6f1lWSThnzqC0+wASKIhlXWglbjWFoQSZytg8mgxeIOs84DIiGVrn0=
