language: java
before_script: cd 12f_app
script: mvn clean install
deploy:
  edge: true
  provider: cloudfoundry
  username: toomas.pappel@smit.ee
  api: https://api.run.pivotal.io
  organization: tp
  space: development
dd:
  secure: PDBz1sssQ+uceUuDlDBwK6GnFD8gIHLaG2poAm4dLQbHcs1RQo94wBWW6U8QREEvZ5BGJ1wB3LjiZtDzUBUmFXknsCL/rF0ZAn7Dgc2nvhgVyqUw/SWq19zWv0KggFnvkYbZ1bCT1JBqJ0RufRNdkdNiQhK3ioVYOiidDgr0OGYC8Rq0ZgO45T6hC9nZi4EcN4/BNuXvvdETEqFE7iWHdJMKM746bUP9+cfL+NANF+NbNONwQ/NJKVXohUkk117I3F6JW+NoNItbEUo6+s2BG5hvP0OA7ETxYQF6D3knn7mF+1ZAaoE75/EHjbSpKBNr7e1/qp1j7TftA8utesesG9QLDM7SvwyvZy4b+p9CpbzfDBd46JFLAcBN3H0tq8PYPlTFiG8uZxy3VWWG8CBRyd9v4xMFkrPNFjR31KTDO1lnoAjxm17phEU6OjiftmOy3HHw1bXHUs0RjQGtUZ3tXqyEA8nTUXr7Tp2DAYgni+FEvg0fi/PORiOFTB5N2w0sr1ZYPdy4FWhOHQGGP8DTqP2xneeeAYFwl+E9AZtyeepnNXWXUiNbH8bQqfl7wkge3fxU1JvTTTLhuXo8Yirey90cCtwgt4kp8LnQ9rTrInwL/3ZELoN+TPhBA6c2CLSet3kED2QlHmcGRoC5jsiqXFG06VY+CCgsz9H6TdjrtdM=
