language: java
before_script: cd 12f_app
script: mvn clean install
deploy:
  edge: true
  provider: cloudfoundry
  username: toomas.pappel@smit.ee
  api: https://api.run.pivotal.io
  organization: tp
  space: development
dd:
secure: "p6EPuE51Xl9nyQpispKY+UvAFksIqnR0uqutjwIBoTWAwZaRyDZHrjE9zznhjl1w0zIPX7uywibmhjz6pviMV1XY0xC/FL0sWLCAq/pNKJ1GCgJmTLRZWGmPMLFz1M9IPma2x054zAXqurd5cqvnaaqGRXVXz1u3S4me6w/Zzbs4+neS9IhCZK9oHjfzqY+voOXrDddqPJRrOPacAOJpaMyMjzUxKaPneXhk83sAitHPaZOaOfmOKk+63TkaeAlAb4j3JTvWTIGkBfi6Acc7nmLg05Yj2ik91PHNDKYbOESZfmEDqVuWlp/Yr3dB/JiVpRmFs+2vUbC2yfpG2QXVqvHQf1nb2CQ2hlgFHum9e1oUgst7miyyLvX6P/qbbZzKX+cFQocmV2f/n6EUGvJejdECTqoXG1RPrjVT6KXc24iI0FEGVEsNQ0H+3CrxDF53+OUoCeC06MXAhN1PkPVtNc838kn/wQzt3XS4vWyfR2VC4RmjrJfrPgL0OLkhvKfFWzBQxo92S7gQaHQ7i4TGGucbEK40Snenwx7i9MMWNMcg3TRdjYMxbmuHPTN8yh8T36AjhEK9TUAENPUQ4/4dRPFsH5+IAvmwnbgzEqvDRGpouTV3MN505gzSAvDaW61IaOJ9EVKNKI2GHJRWTpKrgwCh3JQfVPeohIAIIXc6FDs="