language: java
before_script: cd 12f_app
script: mvn clean install
deploy:
  edge: true
  provider: cloudfoundry
  username: toomas.pappel@smit.ee
  api: https://api.run.pivotal.io
  organization: tp
  space: development